name: Build

on: [push]

jobs:
  build_linux:
    name: Build Linux version
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Init submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: 5.9.1
          target: desktop
          modules: qtwebengine


      - name: Run QMake
        shell: bash
        run: |
          cd src
          qmake Scenarist.pro

      - name: Build
        shell: bash
        run: |
          cd src
          make -j$(nproc)

      - name: Make deb-package
        shell: bash
        run: |
          cp build/Release/bin/scenarist-desktop/Scenarist build/Ubuntu/scenarist_amd64/usr/share/KIT/Scenarist/
          cd build/Ubuntu
          ./make-deb_amd64.sh ci-build


      - name: Collect artifacts
        uses: actions/upload-artifact@v1
        with:
          name: linux packages
          path: build/Ubuntu/scenarist-setup-ci-build_en_amd64.deb
